---
validation:
  existing_tags:
    - name: "div"
      attrs:
        class: "teaser-right twelve"
    - name: "span"
      attrs:
        class: "teaser-right__labeltopline"
  existing_strings_in_tags:
    - include_string: "headline"
      tag:
        name: "span"
        attrs:
          class: "teaser-right__headline"
    - include_string: "Test topline"
      tag:
        name: "span"
        attrs:
          class: "teaser-right__labeltopline"
scraping:
  - id: article_link
    tag:
      name: null
      attrs:
        class: "teaser-right__link"
  - id: topline
    tag:
      name: null
      attrs: 
        class: "teaser-right__labeltopline"
  - id: headline
    tag:
      name: null
      attrs: 
        class: "teaser-right__headline"
  - id: shorttext
    tag:
      name: null
      attrs:
        class: "teaser-right__shorttext"
  - id: date
    tag:
      name: null
      attrs: 
        class: "teaser-right__date"